# keep
spring:
  docker:
    compose:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          dex:
            client-id: base-client
            client-secret: base-secret
            client-name: Login with Dex
            scope:
              - openid
              - email
        provider:
          dex:
            issuer-uri: http://localhost:5556
