version: "3.8"
services:
  authserver:
    image: "bitnami/dex:2.37.0"
    deploy:
      replicas: 1
    configs:
      - source: dex_config
        target: /opt/config/dex.yml
    ports:
      - 5556:5556
    command:
      - serve
      - /opt/config/dex.yml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5556/.well-known/openid-configuration"]
      interval: 1s
      timeout: 1s
      retries: 5

configs:
  dex_config:
    file: ./dex.yml
